In [1]:
import snowflake.connector
import pandas as pd

In [ ]:
# %pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (4.6.0)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (49.0.0)
Requirement already satisfied: pyOpenSSL>=24.0.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (26.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (2.13.0)
Requirement already satisfied: pytz in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (2026.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (2.34.2)
Requirement already satisfied: packaging in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (3.4.7)
Requirement already satisfied: idna<4,>=3.7 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (3.18)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (2026.6.17)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (4.16.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (3.29.6)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (4.10.0)
Requirement already satisfied: tomlkit in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (0.15.0)
Requirement already satisfied: boto3>=1.24 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (1.43.41)
Requirement already satisfied: botocore>=1.24 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python) (1.43.41)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python) (2.7.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (0.19.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from cryptography>=46.0.5->snowflake-connector-python) (2.1.0)
Requirement already satisfied: pycparser in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python) (3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
conn = snowflake.connector.connect(
    user='ABOOD36',
    password='HezMEJkBh2xZ9tx',
    account='itcoyes-gf39385',   # from your URL
    warehouse='TOURISM_WH',
    database='TOURISM_DB',
    schema='GOLD'
)

query = """
SELECT
    f.location_id,
    f.date,
    f.timestamp,
    f.occupancy_rate,
    f.cpi,
    f.anomaly_flag,
    l.location_name,
    l.city,
    l.location_type,
    l.max_capacity,
    d.is_weekend,
    d.calendar_season,
    d.school_period,
    d.month,
    d.quarter,
    q.popularity_tier
FROM GOLD.FCT_CROWD_UNIFIED f
JOIN GOLD.DIM_LOCATION l ON f.location_id = l.location_id
JOIN GOLD.DIM_DATE d ON f.date = d.date
JOIN GOLD.LOCATION_QUALITY_SCORE q ON f.location_id = q.location_id
"""

df = pd.read_sql(query, conn)
print(df.shape)
df.head()

D:\Office\Temp\ipykernel_51792\4253994983.py:34: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

(586360, 16)

,LOCATION_ID,DATE,TIMESTAMP,OCCUPANCY_RATE,CPI,ANOMALY_FLAG,LOCATION_NAME,CITY,LOCATION_TYPE,MAX_CAPACITY,IS_WEEKEND,CALENDAR_SEASON,SCHOOL_PERIOD,MONTH,QUARTER,POPULARITY_TIER
0,SHM_01,2023-12-11,2023-12-11 11:00:00,1.000,0.900,True,Ras Mohammed,Sharm El Sheikh,Nature,5000,False,Winter,School Days,12,4,Tier1
1,SHM_01,2024-01-06,2024-01-06 17:00:00,0.989,0.942,True,Ras Mohammed,Sharm El Sheikh,Nature,5000,True,Winter,Midyear Vacation,1,1,Tier1
2,SHM_01,2023-09-15,2023-09-15 08:00:00,0.672,0.697,False,Ras Mohammed,Sharm El Sheikh,Nature,5000,False,Autumn,School Days,9,3,Tier1
3,SHM_01,2024-01-11,2024-01-11 16:00:00,1.000,0.922,True,Ras Mohammed,Sharm El Sheikh,Nature,5000,False,Winter,Midyear Vacation,1,1,Tier1
4,SHM_01,2024-05-09,2024-05-09 13:00:00,1.000,0.875,True,Ras Mohammed,Sharm El Sheikh,Nature,5000,False,Spring,School Days,5,2,Tier1

In [ ]:
# df = df.drop(columns=['ISLAMIC_HOLIDAY'])

In [5]:
print(df.shape)
print(df.isnull().sum())
print(df['OCCUPANCY_RATE'].describe())

(586360, 16)
LOCATION_ID        0
DATE               0
TIMESTAMP          0
OCCUPANCY_RATE     0
CPI                0
ANOMALY_FLAG       0
LOCATION_NAME      0
CITY               0
LOCATION_TYPE      0
MAX_CAPACITY       0
IS_WEEKEND         0
CALENDAR_SEASON    0
SCHOOL_PERIOD      0
MONTH              0
QUARTER            0
POPULARITY_TIER    0
dtype: int64
count    586360.000000
mean          0.536450
std           0.291274
min           0.031000
25%           0.289000
50%           0.483000
75%           0.784000
max           1.000000
Name: OCCUPANCY_RATE, dtype: float64

In [6]:
df.columns.tolist()

['LOCATION_ID',
 'DATE',
 'TIMESTAMP',
 'OCCUPANCY_RATE',
 'CPI',
 'ANOMALY_FLAG',
 'LOCATION_NAME',
 'CITY',
 'LOCATION_TYPE',
 'MAX_CAPACITY',
 'IS_WEEKEND',
 'CALENDAR_SEASON',
 'SCHOOL_PERIOD',
 'MONTH',
 'QUARTER',
 'POPULARITY_TIER']

In [7]:
# ---- 3. Make sure TIMESTAMP is a real datetime ----
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])

# ---- 4. Feature engineering: time-based features ----
#adding a columns for the hour
df['hour'] = df['TIMESTAMP'].dt.hour
#changes day of the week to numbers
df['day_of_week_num'] = df['TIMESTAMP'].dt.dayofweek  # 0=Monday


# cyclical encoding so hour 23 and hour 0 are "close" to the model
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

# ---- 5. Encode categorical columns as numbers ----
categorical_cols = [
    'LOCATION_ID',
    'CITY',
    'LOCATION_TYPE',
    'POPULARITY_TIER',
    'SCHOOL_PERIOD',
    'CALENDAR_SEASON'
]
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col + '_encoded'] = le.fit_transform(df[col].astype(str))
    encoders[col] = le
# ---- 6. Pick final feature columns ----
feature_cols = [
    'hour_sin',
    'hour_cos',

    'MONTH',
    'QUARTER',

    'IS_WEEKEND',

    'SCHOOL_PERIOD_encoded',
    'CALENDAR_SEASON_encoded',

    'LOCATION_ID_encoded',
    'CITY_encoded',
    'LOCATION_TYPE_encoded',
    'POPULARITY_TIER_encoded',

    'MAX_CAPACITY'
]
X = df[feature_cols]
y = df['OCCUPANCY_RATE']

# ---- 7. Train/test split ----
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

(469088, 12) (117272, 12)

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ---- Train the model ----
model = RandomForestRegressor(
    n_estimators=100,   # number of trees
    random_state=42,    # reproducibility
    n_jobs=-1           # use all CPU cores, trains faster
)

model.fit(X_train, y_train)


#

RandomForestRegressor(n_jobs=-1, random_state=42)

In [9]:
import joblib

joblib.dump(model, "saved_model.pkl")
joblib.dump(encoders, "encoders.pkl")

print("Model saved successfully!")

Model saved successfully!

In [10]:
 #---- Evaluate on the test set ----
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R²   : {r2:.4f}")

MAE  : 0.0468
RMSE : 0.0754
R²   : 0.9331

In [11]:
print(df[['CPI', 'OCCUPANCY_RATE']].corr())

                    CPI  OCCUPANCY_RATE
CPI             1.00000         0.97819
OCCUPANCY_RATE  0.97819         1.00000

In [12]:
importances = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

print(importances)

                    feature  importance
10  POPULARITY_TIER_encoded    0.477388
0                  hour_sin    0.118523
7       LOCATION_ID_encoded    0.089465
1                  hour_cos    0.071069
8              CITY_encoded    0.069360
9     LOCATION_TYPE_encoded    0.038473
2                     MONTH    0.037404
5     SCHOOL_PERIOD_encoded    0.037265
11             MAX_CAPACITY    0.027599
6   CALENDAR_SEASON_encoded    0.016499
3                   QUARTER    0.012427
4                IS_WEEKEND    0.004527

In [13]:
print(df.groupby('POPULARITY_TIER')['OCCUPANCY_RATE'].mean())

POPULARITY_TIER
Tier1    0.693897
Tier2    0.318882
Tier3    0.186184
Name: OCCUPANCY_RATE, dtype: float64

In [14]:
from datetime import timedelta

# ---- 1. Get "tomorrow" relative to your data, not real time ----
max_date_query = "SELECT MAX(date) as max_date FROM GOLD.DIM_DATE"
max_date_result = pd.read_sql(max_date_query, conn)
max_date = pd.to_datetime(max_date_result['MAX_DATE'].iloc[0])
tomorrow = (max_date + timedelta(days=1)).date()

# ---- 2. Get unique locations with their static info ----
locations = df[['LOCATION_ID', 'LOCATION_ID_encoded',
                 'CITY', 'CITY_encoded',
                 'LOCATION_TYPE', 'LOCATION_TYPE_encoded',
                 'POPULARITY_TIER', 'POPULARITY_TIER_encoded',
                 'MAX_CAPACITY']].drop_duplicates(subset=['LOCATION_ID'])

# ---- 3. Calculate tomorrow's calendar info ourselves (DIM_DATE doesn't cover this date) ----
is_weekend_tomorrow = 1 if tomorrow.weekday() >= 5 else 0

# Build a month -> school_period mapping from your real data (do this once)
month_to_period = df[['MONTH', 'SCHOOL_PERIOD']].drop_duplicates().set_index('MONTH')['SCHOOL_PERIOD'].to_dict()

# Then, whenever "tomorrow" changes, look it up automatically:
tomorrow_month = tomorrow.month
school_period_tomorrow = month_to_period[tomorrow_month]
school_period_encoded_tomorrow = encoders['SCHOOL_PERIOD'].transform([school_period_tomorrow])[0]

# ---- 4. Build one row per (location, hour) for tomorrow ----
rows = []
month_tomorrow = tomorrow.month

quarter_tomorrow = (month_tomorrow - 1) // 3 + 1

if month_tomorrow in [12, 1, 2]:
    season = "Winter"
elif month_tomorrow in [3, 4, 5]:
    season = "Spring"
elif month_tomorrow in [6, 7, 8]:
    season = "Summer"
else:
    season = "Autumn"

season_encoded = encoders["CALENDAR_SEASON"].transform([season])[0]

for _, loc in locations.iterrows():
    for hour in range(24):
        hour_sin = np.sin(2 * np.pi * hour / 24)
        hour_cos = np.cos(2 * np.pi * hour / 24)
        rows.append({
            'hour_sin': hour_sin,
            'hour_cos': hour_cos,
            'IS_WEEKEND': is_weekend_tomorrow,
            'SCHOOL_PERIOD_encoded': school_period_encoded_tomorrow,
            'LOCATION_ID_encoded': loc['LOCATION_ID_encoded'],
            'CITY_encoded': loc['CITY_encoded'],
            'LOCATION_TYPE_encoded': loc['LOCATION_TYPE_encoded'],
            'POPULARITY_TIER_encoded': loc['POPULARITY_TIER_encoded'],
            'MAX_CAPACITY': loc['MAX_CAPACITY'],
            'location_id': loc['LOCATION_ID'],
            'city': loc['CITY'],
            'hour': hour,
            'MONTH': month_tomorrow,
            'QUARTER': quarter_tomorrow,
            'CALENDAR_SEASON_encoded': season_encoded,
        })

tomorrow_df = pd.DataFrame(rows)
print(tomorrow_df.shape)
tomorrow_df.head()

D:\Office\Temp\ipykernel_51792\1069702432.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  max_date_result = pd.read_sql(max_date_query, conn)

(1080, 15)

,hour_sin,hour_cos,IS_WEEKEND,SCHOOL_PERIOD_encoded,LOCATION_ID_encoded,CITY_encoded,LOCATION_TYPE_encoded,POPULARITY_TIER_encoded,MAX_CAPACITY,location_id,city,hour,MONTH,QUARTER,CALENDAR_SEASON_encoded
0,0.000000,1.000000,0,0,40,8,5,0,5000,SHM_01,Sharm El Sheikh,0,1,1,3
1,0.258819,0.965926,0,0,40,8,5,0,5000,SHM_01,Sharm El Sheikh,1,1,1,3
2,0.500000,0.866025,0,0,40,8,5,0,5000,SHM_01,Sharm El Sheikh,2,1,1,3
3,0.707107,0.707107,0,0,40,8,5,0,5000,SHM_01,Sharm El Sheikh,3,1,1,3
4,0.866025,0.500000,0,0,40,8,5,0,5000,SHM_01,Sharm El Sheikh,4,1,1,3

In [15]:
# ---- Predict occupancy for tomorrow ----
X_tomorrow = tomorrow_df[feature_cols]  # same feature columns used in training

tomorrow_df['predicted_occupancy'] = model.predict(X_tomorrow)

# quick look
tomorrow_df[['location_id', 'city', 'hour', 'predicted_occupancy']].sort_values(
    ['location_id', 'hour']
).head(30)

     location_id        city  hour  predicted_occupancy
1032      ALX_01  Alexandria     0             0.376237
1033      ALX_01  Alexandria     1             0.381772
1034      ALX_01  Alexandria     2             0.372310
1035      ALX_01  Alexandria     3             0.382257
1036      ALX_01  Alexandria     4             0.373936
1037      ALX_01  Alexandria     5             0.379424
1038      ALX_01  Alexandria     6             0.272330
1039      ALX_01  Alexandria     7             0.272330
1040      ALX_01  Alexandria     8             0.272330
1041      ALX_01  Alexandria     9             0.272166
1042      ALX_01  Alexandria    10             0.270733
1043      ALX_01  Alexandria    11             0.421933
1044      ALX_01  Alexandria    12             0.411295
1045      ALX_01  Alexandria    13             0.610199
1046      ALX_01  Alexandria    14             0.593752
1047      ALX_01  Alexandria    15             0.600972
1048      ALX_01  Alexandria    16             0.465256
1049      ALX_01  Alexandria    17             0.452457
1050      ALX_01  Alexandria    18             0.320384
1051      ALX_01  Alexandria    19             0.391732
1052      ALX_01  Alexandria    20             0.396502
1053      ALX_01  Alexandria    21             0.468935
1054      ALX_01  Alexandria    22             0.680820
1055      ALX_01  Alexandria    23             0.680820
744       ALX_02  Alexandria     0             0.376237
745       ALX_02  Alexandria     1             0.381772
746       ALX_02  Alexandria     2             0.372310
747       ALX_02  Alexandria     3             0.382257
748       ALX_02  Alexandria     4             0.373936
749       ALX_02  Alexandria     5             0.379424

In [16]:
# Overcrowded locations 1PM-3PM
overcrowded = tomorrow_df[
    (tomorrow_df['hour'].between(13, 15)) &
    (tomorrow_df['predicted_occupancy'] > 0.85)
]
print(overcrowded[['location_id', 'city', 'hour', 'predicted_occupancy']])

# Best time in Cairo
cairo = tomorrow_df[tomorrow_df['city'] == 'Cairo']
best_hour = cairo.groupby('hour')['predicted_occupancy'].mean().idxmin()
print("Best hour in Cairo:", best_hour)

     location_id             city  hour  predicted_occupancy
13        SHM_01  Sharm El Sheikh    13             1.000000
14        SHM_01  Sharm El Sheikh    14             1.000000
15        SHM_01  Sharm El Sheikh    15             0.998965
37        FYM_04           Fayoum    13             1.000000
38        FYM_04           Fayoum    14             1.000000
...          ...              ...   ...                  ...
1022      GIZ_03             Giza    14             1.000000
1023      GIZ_03             Giza    15             1.000000
1069      LUX_01            Luxor    13             1.000000
1070      LUX_01            Luxor    14             0.997706
1071      LUX_01            Luxor    15             0.998960

[64 rows x 4 columns]
Best hour in Cairo: 2

In [ ]:
#tomorrow_df.to_csv('tomorrow_predictions.csv', index=False)

In [ ]:
# %pip install "snowflake-connector-python[pandas]"

Requirement already satisfied: snowflake-connector-python[pandas] in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (4.6.0)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (49.0.0)
Requirement already satisfied: pyOpenSSL>=24.0.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (26.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (2.13.0)
Requirement already satisfied: pytz in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (2026.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (2.34.2)
Requirement already satisfied: packaging in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (3.4.7)
Requirement already satisfied: idna<4,>=3.7 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (3.18)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (2026.6.17)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (4.16.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (3.29.6)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (4.10.0)
Requirement already satisfied: tomlkit in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (0.15.0)
Requirement already satisfied: boto3>=1.24 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (1.43.41)
Requirement already satisfied: botocore>=1.24 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from snowflake-connector-python[pandas]) (1.43.41)
Collecting pandas<3.0.0,>=2.1.2 (from snowflake-connector-python[pandas])
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting pyarrow>=14.0.1 (from snowflake-connector-python[pandas])
  Downloading pyarrow-25.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2025.3)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python[pandas]) (2.7.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (0.19.0)
Requirement already satisfied: six>=1.5 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from cryptography>=46.0.5->snowflake-connector-python[pandas]) (2.1.0)
Requirement already satisfied: pycparser in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python[pandas]) (3.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.0 MB 3.3 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 3.3 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/11.0 MB 3.5 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/11.0 MB 3.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.5/11.0 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.0 MB 3.6 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 3.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.0 MB 3.6 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.0 MB 3.6 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.0 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 3.6 MB/s  0:00:03
Downloading pyarrow-25.0.0-cp313-cp313-win_amd64.whl (27.9 MB)
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
    --------------------------------------- 0.5/27.9 MB 3.8 MB/s eta 0:00:08
   -- ------------------------------------- 1.6/27.9 MB 3.7 MB/s eta 0:00:08
   --- ------------------------------------ 2.4/27.9 MB 3.7 MB/s eta 0:00:07
   ---- ----------------------------------- 3.1/27.9 MB 3.7 MB/s eta 0:00:07
   ----- ---------------------------------- 3.9/27.9 MB 3.7 MB/s eta 0:00:07
   ------ --------------------------------- 4.7/27.9 MB 3.7 MB/s eta 0:00:07
   ------- -------------------------------- 5.5/27.9 MB 3.7 MB/s eta 0:00:07
   --------- ------------------------------ 6.3/27.9 MB 3.7 MB/s eta 0:00:06
   --------- ------------------------------ 6.8/27.9 MB 3.7 MB/s eta 0:00:06
   ---------- ----------------------------- 7.6/27.9 MB 3.7 MB/s eta 0:00:06
   ------------ --------------------------- 8.4/27.9 MB 3.7 MB/s eta 0:00:06
   ------------- -------------------------- 9.2/27.9 MB 3.7 MB/s eta 0:00:06
   -------------- ------------------------- 10.0/27.9 MB 3.7 MB/s eta 0:00:05
   --------------- ------------------------ 10.7/27.9 MB 3.7 MB/s eta 0:00:05
   ---------------- ----------------------- 11.5/27.9 MB 3.7 MB/s eta 0:00:05
   ----------------- ---------------------- 12.3/27.9 MB 3.7 MB/s eta 0:00:05
   ------------------ --------------------- 13.1/27.9 MB 3.7 MB/s eta 0:00:04
   ------------------- -------------------- 13.9/27.9 MB 3.7 MB/s eta 0:00:04
   --------------------- ------------------ 14.7/27.9 MB 3.7 MB/s eta 0:00:04
   ---------------------- ----------------- 15.5/27.9 MB 3.7 MB/s eta 0:00:04
   ----------------------- ---------------- 16.3/27.9 MB 3.7 MB/s eta 0:00:04
   ------------------------ --------------- 17.0/27.9 MB 3.7 MB/s eta 0:00:03
   ------------------------- -------------- 17.8/27.9 MB 3.7 MB/s eta 0:00:03
   -------------------------- ------------- 18.4/27.9 MB 3.7 MB/s eta 0:00:03
   --------------------------- ------------ 19.1/27.9 MB 3.7 MB/s eta 0:00:03
   ---------------------------- ----------- 19.9/27.9 MB 3.7 MB/s eta 0:00:03
   ----------------------------- ---------- 20.7/27.9 MB 3.7 MB/s eta 0:00:02
   ------------------------------ --------- 21.5/27.9 MB 3.7 MB/s eta 0:00:02
   ------------------------------- -------- 22.3/27.9 MB 3.7 MB/s eta 0:00:02
   --------------------------------- ------ 23.1/27.9 MB 3.7 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/27.9 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 24.6/27.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/27.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 26.2/27.9 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 27.0/27.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  27.8/27.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 27.9/27.9 MB 3.6 MB/s  0:00:07
Installing collected packages: pyarrow, pandas

   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
  Attempting uninstall: pandas
   ---------------------------------------- 0/2 [pyarrow]
    Found existing installation: pandas 3.0.0
   ---------------------------------------- 0/2 [pyarrow]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
    Uninstalling pandas-3.0.0:
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
      Successfully uninstalled pandas-3.0.0
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Office\AppData\Local\Programs\Python\Python313\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# %pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\office\appdata\local\programs\python\python313\lib\site-packages (25.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from snowflake.connector.pandas_tools import write_pandas

success, nchunks, nrows, _ = write_pandas(
    conn,
    tomorrow_df,
    "TOMORROW_PREDICTIONS",
    schema="GOLD",
    auto_create_table=True
)

In [18]:
print(success, nrows, "rows written")

True 1080 rows written